name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Python (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "macos-14" ]
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Conda setup
        uses: conda-incubator/setup-miniconda@v3
        if: matrix.os != 'macos-14'
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          environment-file: build_envs/environment.yml

      - name: Conda setup (macOS M1)
        uses: conda-incubator/setup-miniconda@v3
        if: matrix.os == 'macos-14'
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Mambaforge-23.11.0-0-MacOSX-arm64.sh
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          environment-file: build_envs/environment.yml

      - name: Build WRF-Python
        run: |
          cd build_scripts
          ./gnu_omp.sh
          cd ..

      - name: Run tests
        run: |
          cd test/ci_tests
          python utests.py

      - name: Send a message
        uses: zulip/github-actions-zulip/send-message@v1
        if: failure()
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: "wrf-python-ci-bot@zulip2.cloud.ucar.edu"
          organization-url: "https://zulip2.cloud.ucar.edu"
          to: "GeoCAT"
          type: "stream"
          topic: "wrf-python CI failures"
          content: "WRF-Python CI failed: https://github.com/NCAR/wrf-python/actions"
